-- INSERT INTO ROOM (NAME, ROOM_NUMBER, BED_INFO) VALUES ('Piccadilly', 'P1', '1Q');
INSERT INTO ACCOUNTS (FIRSTNAME, SURNAME, ACCOUNT_NUMBER) VALUES ('TONY', 'HUANG', '1234');
INSERT INTO ACCOUNTS (FIRSTNAME, SURNAME, ACCOUNT_NUMBER) VALUES ('JOHN', 'SMITH', '1');
INSERT INTO ACCOUNTS (FIRSTNAME, SURNAME, ACCOUNT_NUMBER) VALUES ('TONY', 'HUANG', '1234');
