INSERT INTO ACCOUNTS (FIRSTNAME, SURNAME, ACCOUNT_NUMBER) VALUES ('TONY', 'HUANG', '1234');
INSERT INTO ACCOUNTS (FIRSTNAME, SURNAME, ACCOUNT_NUMBER) VALUES ('JOHN', 'SMITH', '1235');
INSERT INTO ACCOUNTS (FIRSTNAME, SURNAME, ACCOUNT_NUMBER) VALUES ('JAMES', 'MAY', '1236');
INSERT INTO ACCOUNTS (FIRSTNAME, SURNAME, ACCOUNT_NUMBER) VALUES ('HOLLIE', 'ROE', '1237');
